### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by prbond** [yvguim/updatengine-client#1]
Bonjour

Sur mon pc en Win 7 Pro 64 bit avec python 3.3.2 Windows X86-64
quand je lance updatengine-client.py avec ou sans arguments

j'ai cette erreur :

File "C:\Developpement\updatengine-client-master\Windows\updatengine-client.py", line 70
print "Public packages software available on server\n"
SyntaxError: invalid syntax

Une idée ou ça vient de moi d’être un boulet en python ^^

Merci d'avance

**Comment by yvguim** [comment]
Bonjour, 
Une petite idée oui ;-)
Le client est prévu pour fonctionner à partir de sa version packagée pour windows (l'exe embarque dans ce cas tout son environnement de fonctionnement ce qui évite problèmes de dépendances et versions utilisées).

Aussi, pourrais tu réinstaller ton client en suivant la documentation présentée ici: http://www.updatengine.com/installation-agent-updatengine-windows/

Merci,
Yves

**Comment by yvguim** [comment]
Bonjour,

Je me permet de clore cette issue mais n'hésites pas intervenir sur le forum dédié si tu as des questions.
Yves
